### ISSUE TITLE
Typo in ERCOT.md

### ISSUE THREAD

**Issue by sotorrio1** [PERFORM-Forecasts/documentation#10]
There is a typo in the Python examples section. The key 'time-index' doesn't exist and it generates the following error:

```python
KeyError: "Unable to open object (object 'time-index' doesn't exist)"
```

I believe it should be 'time_index'.

**Comment by MRossol** [comment]
@sotorrio1 , bug has been fixed. Thanks.

**Comment by sotorrio1** [comment]
@MRossol Thanks!
