### ISSUE TITLE
MISO ECMWF solar forecast has NA

### ISSUE THREAD

**Issue by xy3134** [PERFORM-Forecasts/documentation#13]
**Bug Description**
2019 MISO ECMWF solar forecast has NA in issue_time.

**File Path**
MISO/2019/ECMWF/Solar_51MemberForecasts/Day_ahead/Site_level/Site_Albany_Solar_solar_1day-ahead_2019.h5

**Comment by bsergi** [comment]
It looks like this is just a case of some issue times being dropped. We have addressed the problem in the data, so this should in the next release to AWS which should take place in the next 2 weeks.

**Comment by bsergi** [comment]
This issue should be resolved in the recent update of dataset so closing this for now, but please re-open or reach out if you continue to encounter it.
