### ISSUE TITLE
Mapping actual/forecasts to PERFORM synthetic grids

### ISSUE THREAD

**Issue by mtanneau** [PERFORM-Forecasts/documentation#15]
Dear NREL team,

I am part of one of the PERFORM projects. Our team is are trying to combine the public actual/forecast data here with the synthetic grids provided by Texas A&M (ERCOT and MISO+SPP grids) and UW-Madison (NYISO grid).

Specifically:
* Is there a one-to-one correspondence between renewable generators in the present data and those in the synthetic grids? If so, can you point us to the best way of matching that data?
* There are multiple versions of the TA&M grids, is the current actual/forecast data based on a specific version? If so, which one?

Many thanks

**Comment by bsergi** [comment]
Sorry for the delayed response on this. Our PERFORM dataset is somewhat independent of the teams developing the synthetic grids; as such, I'm not familiar with any such mapping and our buildouts are not connected to specific versions of the TA&M. The future renewable sites in our data do come with approximate lat/long coordinates--although some of these are summarized only by county--which could be used to connect to nodes in the synthetic grids. 

Happy to chat more about this as useful -- I'm actually not too aware of the how the synthetic grid teams are using our data.

**Comment by mtanneau** [comment]
As far as I can tell: the artificial PERFORM grids have not linked to the data produced by NREL. Some of the Texas A&M have time series data, but they are based on bottom-up approaches. For instance, load profiles are created based on census data + residential/commercial/industrial load types.

All the PERFORM artificial grids of I have seen (ERCOT, ISO-NE and MISO+SPP) use the EIA860 codes to identify generators. Having that information in, e.g, the metadata, would be very useful.

**Comment by bsergi** [comment]
The data sets we produce do include some existing wind and solar facilities, but the majority are proposed facilities from the interconnection queues and thus cannot be mapped to existing EIA860 codes.
