### ISSUE TITLE
Unable to open 2 files at Wind/Forecasts/Intra-hour/Site_level 

### ISSUE THREAD

**Issue by MajidSKhoshghalb** [PERFORM-Forecasts/documentation#3]
Hi

I can't open these two wind forecast files: 1- Site_Hale_1_wind_intra-hour_fcst_2018.h5 and 2- Site_Palo_Duro_wind_intra-hour_fcst_2018.h5

`import h5py
import pandas as pd
import s3fs

#s3_path = 's3://arpa-e-perform/ERCOT/2018/Wind/Forecasts/Intra-hour/Site_level/Site_Hale_1_wind_intra-hour_fcst_2018.h5'
s3_path = 's3://arpa-e-perform/ERCOT/2018/Wind/Forecasts/Intra-hour/Site_level/Site_Palo_Duro_wind_intra-hour_fcst_2018.h5'
fs = s3fs.S3FileSystem(anon=True)
with fs.open(s3_path, 'rb') as s3:
  with h5py.File(s3, 'r') as f:
    df_meta = pd.DataFrame(f['meta'][...])
    issue_time = pd.DatetimeIndex(f['issue_time'][...])
    forecast_time = pd.DatetimeIndex(f['forecat_time'][...])
    wind_fcsts= f['forecasts'][...]`

Thanks in advance!

**Comment by MRossol** [comment]
@fengcong1992 I can't open these files on Eagle either can you re-copy or re-build them:
╰─ h5ls /projects/solfor/perform/ERCOT_data/deliverables3/2018/Wind/Forecasts/Intra-hour/Site_level/Site_Hale_1_wind_intra-hour_fcst_2018.h5
/projects/solfor/perform/ERCOT_data/deliverables3/2018/Wind/Forecasts/Intra-hour/Site_level/Site_Hale_1_wind_intra-hour_fcst_2018.h5: unable to open file

╰─ h5ls /projects/solfor/perform/ERCOT_data/deliverables3/2018/Wind/Forecasts/Intra-hour/Site_level/Site_Palo_Duro_wind_intra-hour_fcst_2018.h5
/projects/solfor/perform/ERCOT_data/deliverables3/2018/Wind/Forecasts/Intra-hour/Site_level/Site_Palo_Duro_wind_intra-hour_fcst_2018.h5: unable to open file

**Comment by MRossol** [comment]
@MajidSKhoshghalb, these have been updated.
