### ISSUE TITLE
Time index issue in ECMWF/Wind_51MemberForecasts

### ISSUE THREAD

**Issue by xy3134** [PERFORM-Forecasts/documentation#5]
Hello,

There is only one time_index (presumably the forecast_time) in 2018/ECMWF/Wind_51MemberForecasts/Day_ahead/Site_level/. Could you add the issue_time as well?

There are a few invalid timestamps (e.g. 'NA 18:00:00+00:00') in 2018/ECMWF/Solar_51MemberForecasts/Day_ahead/Site_level/. Could you fix this?

Thanks,
Xinshuo Yang

**Comment by MRossol** [comment]
@xy3134 Time index issue in ECMWF/Wind_51MemberForecasts: ECMWF wind/solar forecasting files have been regenerated to 1) correct time index, 2) format the datasets, and 3) change file names. The files are being re-synced with AWS now
