### ISSUE TITLE
Site-level intra-hour wind forecast issues

### ISSUE THREAD

**Issue by xy3134** [PERFORM-Forecasts/documentation#8]
Hi,

The intra-hour wind forecast for Loma Pinta II and Loma Pinta Wind have size (70075, 99), while the other wind farms have (70080, 99).

Some forecasts have only 1-hour horizon (e.g., the forecasts issued at 2018-03-11 00:00:00, 2018-03-11 01:00:00). Some forecasts have multiple forecasts for the same ``forecast_time`` (e.g. 2018-03-10 23:00:00). 

Would there be future updates to resolve these issues?

Thanks,
Xinshuo

**Comment by MRossol** [comment]
@xy3134 we are working to fix these issues, I'll post an update once we re-sync them with AWS

**Comment by MRossol** [comment]
@xy3134 , this should be fixed in the most recent data push
