### ISSUE TITLE
Wind day-ahead forecast issue time

### ISSUE THREAD

**Issue by xy3134** [PERFORM-Forecasts/documentation#9]
Hello,

The issue_time and forecast_time in day-ahead probabilistic forecast for wind appear to have different lengths. For example, in 2018/Wind/Forecasts/Day-ahead/Site_level/Site_woodward_mountain_i_ii_wind_farm_wind_day-ahead_fcst_2018.h5, the forecast_time has length 8760 while the issue_time has length 61314. Could you investigate?

Thanks,
Xinshuo

**Comment by fzhang-WZ** [comment]
Hi Xinshuo,

Sorry for the late response. The eagle system is under maintenance this week. The updated dataset will be uploaded next week. 

Best,
Flora

**Comment by xy3134** [comment]
Hi,

Has the data set been updated yet? The day-ahead solar forecasts have the same issue (issue_time has length 61314). Could you fix that as well.

Thanks,
Xinshuo

**Comment by MRossol** [comment]
@xy3134 , this should be fixed in the most recent data push
